# Gurobi Solver Parameters
# Common solver settings
# Feasib_Tol: 1.0e-05           # Constraint (primal) feasibility tolerances.
# Optimal_Tol: 1e-5             # Dual feasibility tolerances.
TimeLimit: 200000             # Limits total time solver. (110000 before change 12102021)
Pre_Solve: 1                  # Controls presolve level. (1 before change 12102021)
Method: 2                    # Algorithm used to solve continuous models (including MIP root relaxation). (2 before change 12102021)

BarHomogeneous: 1
#Gurobi-specific solver settings
# MIPGap: 0.001                  # Relative (p.u. of optimal) mixed integer optimality tolerance for MIP problems (ignored otherwise). (1e-4 before change 12102021)
BarConvTol: 1.0e-03           # Barrier convergence tolerance (determines when barrier terminates). Try setting to 10-3 for 26 zone
NumericFocus: 0               # Numerical precision emphasis.
Crossover: 0               # Barrier crossver strategy. # Set to 1 to include crossover.
PreDual: 0                    # Decides whether presolve should pass the primal or dual linear programming problem to the LP optimization algorithm.
AggFill: 10                   # Allowed fill during presolve aggregation.
