# HiGHS Solver Parameters
# Common solver settings
Feasib_Tol: 1.0e-04        # Primal feasibility tolerance # [type: double, advanced: false, range: [1e-10, inf], default: 1e-07]
Optimal_Tol: 1.0e-04       # Dual feasibility tolerance # [type: double, advanced: false, range: [1e-10, inf], default: 1e-07]
TimeLimit: 5.0             # Time limit # [type: double, advanced: false, range: [0, inf], default: inf]
Pre_Solve: off             # Presolve option: "off", "choose" or "on" # [type: string, advanced: false, default: "choose"]
Method: choose             #HiGHS-specific solver settings # Solver option: "simplex", "choose" or "ipm" # [type: string, advanced: false, default: "choose"]

#highs-specific solver settings

# run the crossover routine for ipx
# [type: string, advanced: "on", range: {"off", "on"}, default: "off"]
run_crossover: "off"
